// Auto-generated by generate_cv.py — do not edit manually.
// Regenerate with:  python generate_cv.py

#set text(font: "Source Sans Pro", size: 10pt, lang: "en")
#set page(
  paper: "a4",
  margin: (left: 1.5cm, right: 1.5cm, top: 1.8cm, bottom: 1.8cm),
)
#set par(justify: true, leading: 0.65em)

// ── Heading styles ──────────────────────────────────────────
#show heading.where(level: 1): it => block(width: 100%)[
  #v(0.8em)
  #text(size: 13pt, weight: "bold", fill: rgb("#1a5276"))[#upper(it.body)]
  #line(length: 100%, stroke: 0.8pt + rgb("#1a5276"))
  #v(0.3em)
]

#show heading.where(level: 2): it => block[
  #v(0.4em)
  #text(size: 11pt, weight: "bold", fill: rgb("#2c3e50"))[#it.body]
  #v(0.15em)
]

#show heading.where(level: 3): it => block[
  #v(0.3em)
  #text(size: 10pt, weight: "bold")[#it.body]
  #v(0.1em)
]

// ── Header ──────────────────────────────────────────────────
#align(center)[
  #text(size: 22pt, weight: "bold", fill: rgb("#1a5276"))[
    JUBÍLIO FILIANO MAÚSSE
  ]
  #v(0.3em)
  _"Senior Data & GIS Officer — ACTED / REACH Initiative"_
  #v(0.3em)
  #text(size: 9pt, fill: rgb("#555555"))[
    Pemba, Cabo Delgado, Moçambique \
    ✉ #link("mailto:jubiliomausse5@gmail.com")[jubiliomausse5@gmail.com]  ·  ☎ +258 84 451 8764 \
    🌐 jubiliomausse.github.io  ·  GitHub: Jubilio  ·  LinkedIn: jubilio-mausse
  ]
]

#v(0.6em)


= Professional Profile

Sou _Jubílio Filiano Maússe_, um profissional de Gestão de Informação e Sistemas de Informação Geográfica (SIG) sediado em Pemba, Moçambique. O meu trabalho foca-se em apoiar operações humanitárias, resposta a emergências, rastreio de deslocamentos, sistemas de monitorização e tomada de decisões baseadas em evidências.
Tenho uma vasta experiência em integração de dados geoespaciais e humanitários, gestão de grandes conjuntos de dados, desenvolvimento de dashboards operacionais, mapeamento de vulnerabilidades baseados em SIG, e apoio à coordenação humanitária através da centralização de dados e monitorização de situações.

== Competências Core
  - _Gestão de Informação Humanitária_ (Centralização de Dados e Monitorização de Situações)
  - _SIG & Análise Espacial_ (Mapeamento de Vulnerabilidades, Sensoriamento Remoto)
  - _MEAL & Qualidade de Dados_ (Sistemas de Monitorização, _Data Quality Assurance_)
  - _Resposta a Emergências_ (Rastreio de Deslocamentos)
  - _Capacitação_ (Capacity Building) e _Desenvolvimento de Dashboards_

== Competências Técnicas
  - ArcGIS Pro, QGIS, Google Earth Engine, Mapbox, GDAL
  - KoBoToolbox, ODK, Kobo REST API
  - Python (GeoPandas, Pandas, NumPy), R, SQL
  - PostgreSQL
  - Power BI, Tableau, Plotly, Advanced Excel

== Experiência Profissional

=== Senior Data & GIS Officer | ACTED / REACH Initiative
_Ago 2025 – Presente_
  - Liderança nas atividades de Gestão de Informação para avaliações humanitárias, sistemas de monitorização e rastreio de deslocamentos.
  - Desenho e gestão de sistemas de recolha de dados digitais usando KoBoToolbox e ODK.
  - Produção de análises SIG, mapas de vulnerabilidade, dashboards e relatórios analíticos.

=== Team Leader – Rapid Response Mechanism (RRM) | ACTED
_Mar 2025 – Abr 2025_
  - Liderança na recolha de dados de emergência e reporte durante respostas humanitárias rápidas.

=== GIS Consultant & Urban Planning Specialist | Delcam Consulting & Services
_2023 – 2024_
  - Condução de análises SIG e gestão de dados espaciais para projetos de planeamento urbano.

=== GIS Technician | BIOFUND – Parque Nacional de Banhine
_2024_
  - Gestão de conjuntos de dados geoespaciais e produção de mapeamento para monitorização de conservação.

== Educação
_Licenciatura em Ciência de Informação Geográfica (BSc)_
Universidade Eduardo Mondlane (2019 – 2023)

== Certificações
  - Advanced Monitoring & Evaluation (FIELD)
  - Introduction to MEAL
  - Spatial Data Science with Python
  - Spatial Data Science with R
  - Geospatial Data Analysis & Remote Sensing

== Línguas
  - _Português:_ Nativo
  - _Inglês:_ Fluente


= Publications & Reports

Lista de relatórios técnicos, artigos e contribuições académicas.

== Artigos e Manuscritos
  - _Maússe, J. F._ (2026). _Mapeamento de zonas potenciais de águas subterrâneas no distrito de Mueda, Norte de Moçambique: Integração de sensoriamento remoto, AHP em SIG e validação com fontes de água._ [Manuscrito não publicado]. Ler Artigo.

== Relatórios REACH / IMPACT Initiatives
_(Nota: Relatórios co-desenvolvidos enquanto parte da equipa REACH. Os relatórios oficiais encontram-se publicados no Resource Centre da REACH.)_
  - _Em atualização._


= Projects

Esta secção destaca projectos chave nos quais estive envolvido, tanto a nível académico como profissional.

== Projectos Humanitários & Avaliação de Necessidades

=== Avaliações Rápidas de Necessidades (RNA) em Cabo Delgado
_Função:_ GIS Officer | _Organização:_ ACTED/IMPACT
  - _Descrição:_ Produção de mapas estáticos e dinâmicos de áreas afetadas por choques para orientar missões inter-agências de resposta rápida.
  - _Ferramentas:_ ArcGIS Pro, QGIS, KoBoToolbox.
  - _Impacto:_ Forneceu informação crítica sobre acessibilidade e deslocamento de populações a parceiros humanitários.

== Projectos Académicos & Investigação

=== Modelação de Zonas de Potencial de Águas Subterrâneas
_Função:_ Investigador Independente
  - _Descrição:_ Uso de AHP num ambiente SIG acoplado a dados de deteção remota para identificar aquíferos potenciais no distrito de Mueda.
  - _Ferramentas:_ Google Earth Engine, QGIS, R.
  - _Produto Final:_ Artigo Técnico.
