"""
generate_cv.py — Generates a Typst CV (cv.typ) from the MyST Markdown pages.

This script reads the same Markdown files that power the website and produces
a single Typst source file. Typst is a modern typesetting system — think of it
as a faster, simpler alternative to LaTeX.

╔══════════════════════════════════════════════════════════════╗
║  CUSTOMISE THIS SECTION — your personal details for the CV  ║
╚══════════════════════════════════════════════════════════════╝
"""

import re
import os
import subprocess
import sys
from pathlib import Path

# ── Author preamble (edit these) ─────────────────────────────
AUTHOR = {
    "firstname": "Jubílio Filiano",
    "lastname": "Maússe",
    "email": "jubiliomausse5@gmail.com",
    "phone": "+258 84 451 8764",
    "homepage": "jubiliomausse.github.io",
    "github": "Jubilio",
    "linkedin": "jubilio-mausse",
    "address": "Pemba, Cabo Delgado, Moçambique",
    "positions": [
        "Senior Data & GIS Officer — ACTED / REACH Initiative",
    ],
}

# ── Which pages to include, and in what order ────────────────
# Each tuple is (section_title_for_cv, path_to_markdown_file).
# Comment out any section you do NOT want in the PDF.
PAGES_DIR = Path(__file__).parent / "pages"
CV_SECTIONS = [
    ("Professional Profile",   PAGES_DIR / "sobre.md"),
    ("Publications & Reports", PAGES_DIR / "publicacoes.md"),
    ("Projects",               PAGES_DIR / "projectos" / "portfolio.md"),
]

# ══════════════════════════════════════════════════════════════
#  Everything below is pipeline logic — no need to edit.
# ══════════════════════════════════════════════════════════════


def strip_frontmatter(text: str) -> str:
    """Remove YAML frontmatter delimited by --- ... ---."""
    return re.sub(r"^---\s*\n.*?\n---\s*\n", "", text, count=1, flags=re.DOTALL)


def strip_myst_directives(text: str) -> str:
    """Remove MyST directives (grid, card, figure, etc.) leaving plain text."""
    # Remove ::::{grid ...} / :::{card ...} / :::: / ::: blocks
    text = re.sub(r"^:{2,4}\{[^}]*\}.*$", "", text, flags=re.MULTILINE)
    text = re.sub(r"^:{2,4}\s*$", "", text, flags=re.MULTILINE)
    # Remove ```{figure} ... ``` blocks
    text = re.sub(r"^```\{[^}]*\}.*?^```", "", text, flags=re.MULTILINE | re.DOTALL)
    # Remove :option: lines (e.g. :name:, :width:, :align:)
    text = re.sub(r"^:[a-z_]+:.*$", "", text, flags=re.MULTILINE)
    # Remove markdown links but keep text:  [text](url) -> text
    text = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", text)
    # Remove lines that are just a CV download link (not useful inside the CV itself)
    text = re.sub(r"^.*Descarregar o meu Curr.*$", "", text, flags=re.MULTILINE)
    # Strip emoji characters from headings (they don't render well in Typst PDF)
    text = re.sub(
        r"[\U0001F300-\U0001F9FF\U00002702-\U000027B0\U0000FE00-\U0000FE0F\U0000200D]+\s*",
        "", text
    )
    return text


def md_to_typst_items(text: str) -> str:
    """Convert Markdown bullet items and bold/italic to Typst markup."""
    lines = []
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("//"):
            continue
        # Convert markdown bold **text** to Typst *text*
        stripped = re.sub(r"\*\*([^*]+)\*\*", r"*\1*", stripped)
        # Convert markdown italic *text* (single) to Typst _text_
        stripped = re.sub(r"(?<!\*)\*([^*]+)\*(?!\*)", r"_\1_", stripped)
        # Bullet items
        if stripped.startswith("- "):
            lines.append(f"  - {stripped[2:]}")
        elif stripped.startswith("### "):
            lines.append(f"\n=== {stripped[4:]}")
        elif stripped.startswith("## "):
            lines.append(f"\n== {stripped[3:]}")
        elif stripped.startswith("# "):
            continue  # skip top-level headings (we use section titles)
        else:
            lines.append(stripped)
    return "\n".join(lines)


def read_section(filepath: Path) -> str:
    """Read a markdown file and return cleaned Typst content."""
    if not filepath.exists():
        return f"// File not found: {filepath.name}\n"
    raw = filepath.read_text(encoding="utf-8")
    raw = strip_frontmatter(raw)
    raw = strip_myst_directives(raw)
    return md_to_typst_items(raw)


def gen_preamble() -> str:
    """Generate the Typst document preamble with author info."""
    a = AUTHOR
    positions_block = " \\\\\n  ".join(
        f"_\"{p}\"_" for p in a["positions"]
    )

    return f'''// Auto-generated by generate_cv.py — do not edit manually.
// Regenerate with:  python generate_cv.py

#set text(font: "Source Sans Pro", size: 10pt, lang: "en")
#set page(
  paper: "a4",
  margin: (left: 1.5cm, right: 1.5cm, top: 1.8cm, bottom: 1.8cm),
)
#set par(justify: true, leading: 0.65em)

// ── Heading styles ──────────────────────────────────────────
#show heading.where(level: 1): it => block(width: 100%)[
  #v(0.8em)
  #text(size: 13pt, weight: "bold", fill: rgb("#1a5276"))[#upper(it.body)]
  #line(length: 100%, stroke: 0.8pt + rgb("#1a5276"))
  #v(0.3em)
]

#show heading.where(level: 2): it => block[
  #v(0.4em)
  #text(size: 11pt, weight: "bold", fill: rgb("#2c3e50"))[#it.body]
  #v(0.15em)
]

#show heading.where(level: 3): it => block[
  #v(0.3em)
  #text(size: 10pt, weight: "bold")[#it.body]
  #v(0.1em)
]

// ── Header ──────────────────────────────────────────────────
#align(center)[
  #text(size: 22pt, weight: "bold", fill: rgb("#1a5276"))[
    {a["firstname"].upper()} {a["lastname"].upper()}
  ]
  #v(0.3em)
  {positions_block}
  #v(0.3em)
  #text(size: 9pt, fill: rgb("#555555"))[
    {a["address"]} \\
    ✉ {a["email"]}  ·  ☎ {a["phone"]} \\
    🌐 {a["homepage"]}  ·  GitHub: {a["github"]}  ·  LinkedIn: {a["linkedin"]}
  ]
]

#v(0.6em)
'''


def gen_section(title: str, content: str) -> str:
    """Wrap content in a Typst level-1 heading section."""
    return f"\n= {title}\n\n{content}\n"


def create_cv_typ():
    """Assemble the full cv.typ from preamble + page sections."""
    parts = [gen_preamble()]

    for section_title, md_path in CV_SECTIONS:
        content = read_section(md_path)
        parts.append(gen_section(section_title, content))

    cv_typ = "\n".join(parts)

    out = Path(__file__).parent / "cv.typ"
    out.write_text(cv_typ, encoding="utf-8")
    print(f"[OK] Generated {out}  ({len(cv_typ):,} chars)")


    # Compilation is now handled by deploy.yml
    pass


if __name__ == "__main__":
    create_cv_typ()
